from decouple import config
API_ID = config('API_ID')
API_HASH = config('API_HASH')
FREELANCE_ETHIOPIA_CHANNEL_ID = config('FREELANCE_ETHIOPIA_CHANNEL_ID')
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN')
TWILIO_FROM_PHONE_NUMBER = config('TWILIO_FROM_PHONE_NUMBER')
